# Use an official Ubuntu 18.04 runtime as a parent image
FROM ubuntu:bionic

# Update the base OS and install Curl, Python3 and PIP
RUN apt-get update && \
apt-get dist-upgrade -y \
  && apt-get install -y \
                curl \
                python3 \
                python3-dev \
  && curl https://bootstrap.pypa.io/get-pip.py -o /root/get-pip.py \
  && $(which python3) /root/get-pip.py \
  && $(which pip3) install ansible

# Install tini for run-non-root's --init option.
ADD https://github.com/krallin/tini/releases/download/v0.18.0/tini-static /usr/local/bin/tini
RUN chmod +rx /usr/local/bin/tini

# Add Generic way to run things as non-Root user
ADD https://raw.githubusercontent.com/creemama/run-non-root/master/run-non-root.sh /usr/local/bin/run-non-root
RUN chmod +rx /usr/local/bin/run-non-root

# Warn users if they are running as root.
# See the "Invoked with name sh" section of
# https://www.gnu.org/software/bash/manual/html_node/Bash-Startup-Files.html .
# See also https://www.tldp.org/LDP/Linux-Filesystem-Hierarchy/html/etc.html .
ENV ENV /etc/profile
RUN printf "%s" "if [ "\$\(whoami\)" = 'root' ]; then printf \"\n\033[1;31m%s\033[0m\n\n\" \"WARNING: YOU ARE RUNNING AS THE ROOT USER!\"; fi" \
 >> /etc/profile.d/warn-root.sh

# Generate the inventory files
RUN mkdir -p /etc/ansible/ && echo "[local]\nlocalhost ansible_connection=local\n\n[ubuntu-bionic]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

# using tail at the ENTRYPOINT keeps the container running so we can execute commands against it
#ENTRYPOINT ["tail", "-f", "/dev/null"]
ENTRYPOINT ["run-non-root"]
CMD ["--init"]
