# https://github.com/docker/cli/issues/2762#issuecomment-776298308
# ARG PYTHON=3.7

# Use an official Ubuntu Minimal 18.04 runtime as a parent image
FROM ubuntu:bionic AS base
LABEL maintainer="MORGANGRAPHICS, INC"
ARG PYTHON=3.7
ARG USER=ansible-test
ARG PYTHON_VERSION=$PYTHON

# Update the base OS, install dumb-init, Curl, Sudo
# Create Non ROOT User
# When you clean up the apt cache by removing /var/lib/apt/lists it
# reduces the image size, since the apt cache is not stored in a layer.
RUN apt-get -y update \
    && apt-get -y dist-upgrade \
    && apt install -y software-properties-common \
    dumb-init \
    curl \
    git \
    sudo \
    wget \
    && rm -rf /var/lib/apt/lists/* \
    && adduser --disabled-password --gecos '' ${USER} \
    && adduser ${USER} sudo \
    && echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

# Install Python && PIP
RUN add-apt-repository -y ppa:deadsnakes/ppa \
    && apt-get install -y python${PYTHON_VERSION} \
    && update-alternatives --install /usr/bin/python python /usr/bin/python${PYTHON_VERSION} 10 \
    && curl https://bootstrap.pypa.io/get-pip.py -o /root/get-pip.py \
    && $(which python) /root/get-pip.py \
    && update-alternatives --install /usr/bin/pip pip $(which pip3) 10

# Warn users if they are running as root. See the "Invoked with name sh" section of
# https://www.gnu.org/software/bash/manual/html_node/Bash-Startup-Files.html .
# See also https://www.tldp.org/LDP/Linux-Filesystem-Hierarchy/html/etc.html .
ENV ENV /etc/profile
RUN printf "%s" "if [ "\$\(whoami\)" = 'root' ]; then printf \"\n\033[1;31m%s\033[0m\n\n\" \"WARNING: YOU ARE RUNNING AS THE ROOT USER!\"; fi" \
 >> /etc/profile.d/warn-root.sh

# Run install as user
USER ${USER}
# Set working Directory
WORKDIR /home/${USER}/

# Copy Ansible Test inventory file
COPY ./inventory /etc/ansible/
COPY ./requirements.txt .

# Update the Path Environment Variable to include the local Python install
ENV PATH "$PATH:/home/${USER}/.local/bin"

# Install the App requirements
RUN pip install -r requirements.txt
